spring:
 main:
  web-application-type: reactive 
 application:
  name: gateway
 cloud:
  gateway:
   globalcors:
    corsConfigurations:
     '[/**]':
      allowedOrigins: "http://localhost:4200"
      allowedMethods: "*"
      allowedHeaders: "*"
      allowCredentials: true
   routes:
    - id: UserAuth
      uri: http://localhost:9890
      predicates:
        - Path= /security/**
      filters:
       - AuthenticationFilter
    - id: productmanagement
      uri: http://localhost:8081
      predicates:
        - Path=/api/v1/inventory/**
      filters:
        - AuthenticationFilter
    - id: supplier
      uri: http://localhost:9090
      predicates:
        - Path=/supplier/**
      filters:
       - AuthenticationFilter
    - id: ordermanagement
      uri: http://localhost:9000
      predicates:
        - Path=/orders/**
      filters:
       - AuthenticationFilter
    - id: TrackingInventory
      uri: http://localhost:8082
      predicates:
       - Path=/alerts/**
      filters:
       - AuthenticationFilter



eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
